#!/bin/sh /etc/rc.common

START=99

#USE_PROCD=1
NAME=loratx
PROG=/usr/sbin/loratx

init_reset_gpio(){
	[ -d /sys/class/gpio/gpio17 ] || {
	echo "17" > /sys/class/gpio/export
	}
	echo "out" > /sys/class/gpio/gpio17/direction

	sleep 1
	echo "0" > /sys/class/gpio/gpio17/value

	usleep 5000

	echo "1" > /sys/class/gpio/gpio17/value

	sleep 1
}

start() {

	init_reset_gpio

	$PROG /etc/conf.json
}

stop() {
	killall $PROG
}

